### ISSUE TITLE
cannot add server

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#2] opened 2016-05-25 21:40 UTC
I cannot yet add servr. I see exception and nothing (i don't have json file yet)

![f1](https://cloud.githubusercontent.com/assets/4154978/15557210/db2a9f04-22e2-11e6-9c00-7651255c5279.png)

~~~
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_ftp/__init__.py", line 303, in action_new_server
    self.options["servers"].append(server_info)
AttributeError: 'Command' object has no attribute 'options'
~~~

**Comment by pohmelie** [comment] 2016-05-26 09:44
Can't reproduce this. What was your sequence?

**Comment by Alexey-T** [comment] 2016-05-26 09:47
Pls del all configs; and try

**Comment by pohmelie** [comment] 2016-05-26 09:54
I remove `settings` directory, but still no error on add server.

**Comment by Alexey-T** [comment] 2016-05-26 10:24
on_start wasnot called. If plugin installed (no restart yet, so no on_start yet).So ftp shows this err

**Comment by pohmelie** [comment] 2016-05-26 10:28
Hm, so… it's right after install issue? How this should be fixed? If I add some `on_start` initialization to `__init__` it will be initialized even if plugin is off?

**Comment by Alexey-T** [comment] 2016-05-26 10:32
`__init` is called when plugin called (now when it is off)..

**Comment by pohmelie** [comment] 2016-05-26 10:37
Ok, I will move `on_start` code to `__init__`

**Closed** 2016-05-26 14:19 UTC

**Comment by Alexey-T** [comment] 2016-05-26 14:24
.inf still holds on_start.
so error:  AttributeError: 'Command' object has no attribute 'on_start'

**Comment by Alexey-T** [comment] 2016-05-26 14:25
done

**Comment by Alexey-T** [comment] 2016-05-26 14:35
Plugins/Ftp item now don't show servers (shows Ftp panel but not servers in it)
